<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBaqNWvS\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBaqNWvS/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBaqNWvS.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBaqNWvS\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerBaqNWvS\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'BaqNWvS',
    'container.build_id' => '86fbefdf',
    'container.build_time' => 1610716640,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBaqNWvS');
