<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    'truck_zhazgul_index' => [[], ['_controller' => 'App\\Controller\\TruckZhazgulController::index'], [], [['text', '/truck/zhazgul/']], [], []],
    'truck_zhazgul_new' => [[], ['_controller' => 'App\\Controller\\TruckZhazgulController::new'], [], [['text', '/truck/zhazgul/new']], [], []],
    'truck_zhazgul_show' => [['id'], ['_controller' => 'App\\Controller\\TruckZhazgulController::show'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/truck/zhazgul']], [], []],
    'truck_zhazgul_edit' => [['id'], ['_controller' => 'App\\Controller\\TruckZhazgulController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id'], ['text', '/truck/zhazgul']], [], []],
    'truck_zhazgul_delete' => [['id'], ['_controller' => 'App\\Controller\\TruckZhazgulController::delete'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/truck/zhazgul']], [], []],
    'search_form' => [[], ['_controller' => 'App\\Controller\\TruckZhazgulController::searchModelForm'], [], [['text', '/truck/zhazgul/search/form']], [], []],
    'search_id' => [[], ['_controller' => 'App\\Controller\\TruckZhazgulController::searchID'], [], [['text', '/truck/zhazgul/search/id']], [], []],
    'search_model' => [[], ['_controller' => 'App\\Controller\\TruckZhazgulController::searchModel'], [], [['text', '/truck/zhazgul/search/model']], [], []],
    'search_year' => [[], ['_controller' => 'App\\Controller\\TruckZhazgulController::searchYear'], [], [['text', '/truck/zhazgul/search/year']], [], []],
    'search_owner' => [[], ['_controller' => 'App\\Controller\\TruckZhazgulController::searchOwner'], [], [['text', '/truck/zhazgul/search/owner']], [], []],
    'search_price' => [[], ['_controller' => 'App\\Controller\\TruckZhazgulController::searchPrice'], [], [['text', '/truck/zhazgul/search/price']], [], []],
    'zhazgul_kadyrbekova' => [[], ['_controller' => 'App\\Controller\\ZhazgulKadyrbekovaController::index'], [], [['text', '/zhazgul/kadyrbekova']], [], []],
];
